// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "transition-pskel.hpp"

#include "state_pointer_type-pskel.hpp"

#include "probability_type-pskel.hpp"

// transition_pskel
//

void transition_pskel::
to_parser (::state_pointer_type_pskel& p)
{
  this->to_parser_ = &p;
}

void transition_pskel::
probability_parser (::probability_type_pskel& p)
{
  this->probability_parser_ = &p;
}

void transition_pskel::
reward_parser (::xml_schema::decimal_pskel& p)
{
  this->reward_parser_ = &p;
}

void transition_pskel::
parsers (::state_pointer_type_pskel& to,
         ::probability_type_pskel& probability,
         ::xml_schema::decimal_pskel& reward)
{
  this->to_parser_ = &to;
  this->probability_parser_ = &probability;
  this->reward_parser_ = &reward;
}

transition_pskel::
transition_pskel ()
: to_parser_ (0),
  probability_parser_ (0),
  reward_parser_ (0),
  v_state_attr_stack_ (sizeof (v_state_attr_), &v_state_attr_first_)
{
}

// transition_pskel
//

void transition_pskel::
to (::marl::state*)
{
}

void transition_pskel::
probability (float)
{
}

void transition_pskel::
reward (double)
{
}

#include <cassert>

// Attribute validation and dispatch functions for transition_pskel.
//
bool transition_pskel::
_attribute_impl_phase_one (const ::xml_schema::ro_string& ns,
                           const ::xml_schema::ro_string& n,
                           const ::xml_schema::ro_string& s)
{
  if (n == "to" && ns.empty ())
  {
    if (this->to_parser_)
    {
      this->to_parser_->pre ();
      this->to_parser_->_pre_impl ();
      this->to_parser_->_characters (s);
      this->to_parser_->_post_impl ();
      this->to (this->to_parser_->post_state_pointer_type ());
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->to = true;
    return true;
  }

  if (n == "probability" && ns.empty ())
  {
    if (this->probability_parser_)
    {
      this->probability_parser_->pre ();
      this->probability_parser_->_pre_impl ();
      this->probability_parser_->_characters (s);
      this->probability_parser_->_post_impl ();
      this->probability (this->probability_parser_->post_probability_type ());
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->probability = true;
    return true;
  }

  if (n == "reward" && ns.empty ())
  {
    if (this->reward_parser_)
    {
      this->reward_parser_->pre ();
      this->reward_parser_->_pre_impl ();
      this->reward_parser_->_characters (s);
      this->reward_parser_->_post_impl ();
      this->reward (this->reward_parser_->post_decimal ());
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->reward = true;
    return true;
  }

  return false;
}

void transition_pskel::
_pre_a_validate ()
{
  this->v_state_attr_stack_.push ();
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  as.to = false;
  as.probability = false;
  as.reward = false;
}

void transition_pskel::
_post_a_validate ()
{
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  if (!as.to)
    this->_expected_attribute (
      "", "to");
  if (!as.probability)
    this->_expected_attribute (
      "", "probability");
  if (!as.reward)
    this->_expected_attribute (
      "", "reward");

  this->v_state_attr_stack_.pop ();
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

